stages:
    - test
    - build
    - deploy

variables:
    IMAGE_NAME: "faresi/django-demo-app"
    IMAGE_TAG: "latest"


run_tests:
    stage: test
    image: python:3.11
    before_script:
        - pip install pipenv
        - pipenv install --system
    script:
        - python manage.py test

build_image:
    stage: build
    image: docker:24.0-cli
    services:
        - docker:24.0-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    script:
        - docker image build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker image push $IMAGE_NAME:$IMAGE_TAG

deploy:
    stage: deploy
    image: alpine:latest
    before_script:
        - apk add --update --no-cache openssh
        - scp -P 1999 -o StricHostKeyChecking=no -i $SSH_KEY_FILE ./docker-compose.yml deployer@65.109.10.128:/home/deployer/runner
    script:
        - echo "Deploying!"